---
name: Update Fire Stats CSV
concurrency:
  group: fire-stats
  cancel-in-progress: false
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Generate CSV
        run: python scrape.py
      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add data.csv

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "Update fire stats"

          git pull --rebase origin main

          git push origin HEAD:main
      - name: Update chart
        env:
          URL_BASE: ${{secrets.URL_BASE}}
          TOKEN: ${{ secrets.TOKEN }}
        run: python update_chart.py
